golang/go1.11.4.linux-amd64.tar.gz:
  size: 126643341
  object_id: 18a5e777-2d8d-4bac-72c1-ab01f14186f2
  sha: 52bd8eb353a39138a2ddf053857a0fd13f1f176c
jumpbox/bins/bosh:
  size: 29314269
  object_id: cbb4253e-bf1f-416c-6125-6051e713a50f
  sha: 8aa040751158c39cbbb8fa78e4c7a292eb8bff7d
jumpbox/bins/certstrap:
  size: 5493848
  object_id: 6050fa1f-105b-4ddb-8074-224e149b5c83
  sha: 1fa8434399124dd0b17c20c0c90bc34fb0ba16bf
jumpbox/bins/cf:
  size: 21679424
  object_id: 91bc7e7a-c95c-4e1d-78aa-161e24f2091c
  sha: sha256:3fb6d05d31a35b8de19ef5516e60a87792d46baf9ef0b1aaa953adbc0859e35b
jumpbox/bins/credhub:
  size: 10541593
  object_id: 32e2317f-0652-48e0-7c94-5edafc92dc96
  sha: d801fffa9e995abdd9e3a332cca3e76f0b505f0b
jumpbox/bins/esuf:
  size: 7305569
  object_id: 0be72af5-e610-4a05-7ce8-438a32ae1358
  sha: 73979dd7fcb704a0994d55c416340d2d3bcf16df
jumpbox/bins/fly:
  size: 17483867
  object_id: 4c5ddcb2-0435-4885-59bd-cc7419eab24d
  sha: 0e0c263a0f25a946ef9b6526a70285d164383cf4
jumpbox/bins/genesis:
  size: 215376
  object_id: 61dbd808-a496-4ced-7db9-a56bbc3d62e5
  sha: sha256:448dc38bbdcd41ac07f0b91efb7121b9e445c707ddf9fcee36a45bec72cdc028
jumpbox/bins/jq:
  size: 3027945
  object_id: d2d8fb46-86fb-4df8-4b84-3da06ffda574
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
jumpbox/bins/nats:
  size: 7040936
  object_id: 698b0c19-976d-4161-81f3-03b859fe55ff
  sha: 39f00b44c10e332df5f0bff518c1aa2a4dc74792
jumpbox/bins/safe:
  size: 8305617
  object_id: cb013648-7b86-4c16-45f4-02fc4a483492
  sha: 9e2953994c0a59511a99b7d7fbf0ddef2f6aaf14
jumpbox/bins/shield:
  size: 7831586
  object_id: ecd77dc0-f374-423e-5ab9-c95b84659d7b
  sha: f74c76588d37c7b73c6bad7346a4f07e56775c57
jumpbox/bins/spiff:
  size: 5063744
  object_id: eefcc937-c44a-4298-a56d-5e7259137c7c
  sha: 7489aa87ad7f5b3b774fc8a03ccda65860b1374c
jumpbox/bins/terraform:
  size: 89483552
  object_id: f0c8112b-a7c3-4722-7f55-fb3bf204742c
  sha: 8d62bbc6e6a13851e087d3d13bc65377375c35da
jumpbox/bins/tmate:
  size: 2748936
  object_id: 3253b6dc-3e45-4dd2-b6ce-deb1147b853b
  sha: 7dae88002cfc9686fa90e1535e17a2eae22407ea
jumpbox/bins/vault:
  size: 85734099
  object_id: 776aec93-754d-44a4-4262-12efa2e68844
  sha: d0e1eedba1570e9eae59eccdb2f2ba640acff49a
jumpbox/cloudfoundry-utils//cert_generator:
  size: 6667
  object_id: 5aebab56-9a99-4335-75da-82a50da559c8
  sha: sha256:3d73ca8ba53b8b640aaa3c3661122d1f138dff49424e86a573512a9ff19de9e5
jumpbox/cloudfoundry-utils//cf-app-env-json:
  size: 610
  object_id: 8a1cd94a-b2cc-4cf5-79a0-f2190654320b
  sha: sha256:3b9772d6bffb06415a8a7e627bbcab6879ef45024155b5126aea0fcbc7f6566a
jumpbox/cloudfoundry-utils//cf-apps-for-route:
  size: 2456
  object_id: 897eaa31-247c-4a55-67b9-5152baaa1892
  sha: sha256:84be46efa082f8b2cf6256998203f36d4190785ebb6c8b064c40e7b3b11796d9
jumpbox/cloudfoundry-utils//cf-list-org-names:
  size: 472
  object_id: a0b9394b-c2ca-4cd0-5e09-3be0176da0ec
  sha: sha256:1749efe944319a53de6c0a0362c91a86c92b6a274b8fcac83847974dffc5b499
jumpbox/cloudfoundry-utils//cf-services-for-broker:
  size: 4761
  object_id: 3590ea0c-48a7-4b07-4aef-a0e85f0ff1f5
  sha: sha256:0fe41d69984033e7dcd4553185ad6172719e6050303d349357b0bb39cf00dbfc
jumpbox/cloudfoundry-utils//cf-verify:
  size: 3820
  object_id: 0ed5fa63-a267-4dab-753f-465a0968f0f6
  sha: sha256:f004210c625fa78f6a16228f97094fceaaa4b2567229719c9a3cb127aead44ae
jumpbox/cloudfoundry-utils//commit_sha:
  size: 40
  object_id: 421e6013-47db-4f0f-5b37-387734e7c88b
  sha: sha256:6e43a278b50bc426ebde3a6665c0c8f02d50590e29852d5811479838cf59e3bb
jumpbox/cloudfoundry-utils//release-differ:
  size: 2199
  object_id: 50a037dd-1989-4178-4ce9-f4ff27aec50f
  sha: sha256:ae517eb0fce65c4a238b362c9861778ccad4a8d476f21d26a16dea291a00e203
jumpbox/curl-7.63.0.tar.gz:
  size: 4024015
  object_id: d7215770-b813-458d-7099-8e80814c43b2
  sha: b2cb51ac6451728dda191f307db30797629ca14d
jumpbox/git-2.20.1.tar.gz:
  size: 7962304
  object_id: 2cf0a85d-350e-416d-4a01-cd6a9978fe6f
  sha: 6439fb9afc9366f7bf1ddf8bfbe59998e0450ed3
jumpbox/libevent-2.1.8-stable.tar.gz:
  size: 1026485
  object_id: 6ff08733-8696-43ac-7df5-bd0751fef1fd
  sha: 2a1b8bb7a262d3fd0ed6a080a20991a6eed675ec
jumpbox/tmux-2.8.tar.gz:
  size: 491195
  object_id: 96975804-9732-45a4-69d2-4fa8e76a6ab1
  sha: 6a469769a242c95dc8aec443b436d4f8f279f517
jumpbox/tree-1.7.0.tar.gz:
  size: 47082
  object_id: 14f6d45c-aaeb-4dc3-89c9-5ff370553d49
  sha: 35bd212606e6c5d60f4d5062f4a59bb7b7b25949
jumpbox/unzip60.tar.gz:
  size: 1376845
  object_id: 7317d283-62f1-40d3-851a-10418da85106
  sha: abf7de8a4018a983590ed6f5cbd990d4740f8a22
jumpbox/vim-8.1.0789.tar.gz:
  size: 14061297
  object_id: d85b9def-f1bd-40e5-7708-4bb11d40f0df
  sha: bfa10769ca8021316cade7811487f76060e804ab
jumpbox/wget-1.20.tar.gz:
  size: 4474641
  object_id: 5a8f0603-97cc-4bc1-7f9e-ab2ef1f85577
  sha: 467c0ec7dab302cf1826970c1925999d64a6ee9d
jumpbox/zip30.tar.gz:
  size: 1118845
  object_id: f46a1f21-a9e9-415a-9e2d-8b8303fe1659
  sha: c9f4099ecf2772b53c2dd4a8e508064ce015d182
