---
golang_1.5/go1.5.3.linux-amd64.tar.gz:
  object_id: 5d8b0264-6ad9-405e-961f-4449dd9a180f
  sha: c5377eca4837968d043b681f00a852a262f0f5f6
  size: 80147269
jumpbox/bins/bosh-init:
  object_id: 744322bb-be75-43a2-92ca-f5353bd2ec2b
  sha: 7284ab6ac28289c6dafc6f3e4048564423aab77a
  size: 14658552
jumpbox/bins/cf:
  object_id: 638daa39-1ce7-401e-b7ab-003279e81f10
  sha: f9ec7504a53219c9d9c1f0c8857495e3069590fb
  size: 22235914
jumpbox/bins/genesis:
  object_id: 3d865507-4a4a-4e84-883d-7f2e6c1d4e1e
  sha: 3f38be17bd179a083aa900be6d634120652eb1b2
  size: 156392
jumpbox/bins/safe:
  object_id: b3fd648d-d317-46f7-b5be-1cb8e3b3dd17
  sha: 42f436c53a8566c3bc08acd0654eb76be71b808c
  size: 7439314
jumpbox/bins/shield:
  object_id: 0fe0d6e1-8545-43d9-a84f-938594598963
  sha: 34d3dd2619ab3daa5639791caa6c8e70d842a6f2
  size: 8175536
jumpbox/bins/spiff:
  object_id: eefcc937-c44a-4298-a56d-5e7259137c7c
  sha: 7489aa87ad7f5b3b774fc8a03ccda65860b1374c
  size: 5063744
jumpbox/bins/spruce:
  object_id: 6a9a03ce-9271-40e9-8d1b-9876cdfc160f
  sha: 9ad38c8aadd2e8686c626cbea5c038c4825cfaa0
  size: 8622195
jumpbox/bins/vault:
  object_id: 69b6532c-4cbc-4b46-bdc4-fdf1e1625af9
  sha: 507f1c2051d39ab571756aee560b79489ffcabf4
  size: 39822560
jumpbox/curl-7.50.3.tar.gz:
  object_id: dab8c17e-f200-423e-8421-27c80bcaa15d
  sha: be0065afc76a3d8568f5f78d8efddadb6310f9d7
  size: 8908593
jumpbox/git-2.10.0.tar.gz:
  object_id: 8cbf7d51-f1f3-4e7d-a519-f5609bb5a7bc
  sha: 2d588afe7adb11ea11e0787c4a2f01329a0f2f55
  size: 6048363
jumpbox/jq-1.5.tar.gz:
  object_id: 68bdc70f-d6a7-4f31-b29b-e1da48c81371
  sha: 6eef3705ac0a322e8aa0521c57ce339671838277
  size: 739309
jumpbox/libevent-2.0.22-stable.tar.gz:
  object_id: a1541bd8-921a-4c62-9971-19260c2fde62
  sha: a586882bc93a208318c70fc7077ed8fca9862864
  size: 854987
jumpbox/pwgen-2.07.tar.gz:
  object_id: 84046d87-6931-41cb-afb0-c806acc8dfeb
  sha: 51180f9cd5530d79eea18b2443780dec4ec5ea43
  size: 53513
jumpbox/tmux-2.2.tar.gz:
  object_id: 645ddc79-20dd-4145-8ee8-e39c57539ea4
  sha: 5ed1430bc7ef44c227e64e9401c686573dd0791a
  size: 466852
jumpbox/tree-1.7.0.tar.gz:
  object_id: 14f6d45c-aaeb-4dc3-89c9-5ff370553d49
  sha: 35bd212606e6c5d60f4d5062f4a59bb7b7b25949
  size: 47082
jumpbox/unzip60.tar.gz:
  object_id: 7317d283-62f1-40d3-851a-10418da85106
  sha: abf7de8a4018a983590ed6f5cbd990d4740f8a22
  size: 1376845
jumpbox/vim-7.4.tar.bz2:
  object_id: f109912f-1ea4-4e05-b467-fbb2f93f30b9
  sha: 601abf7cc2b5ab186f40d8790e542f86afca86b7
  size: 9843297
jumpbox/wget-1.18.tar.gz:
  object_id: 4e1e8e75-739f-48b8-aff5-ad9b0073dd65
  sha: 28a82e7de2eed38516c7d6e172ec7b9e43dc6c66
  size: 3865525
jumpbox/zip30.tar.gz:
  object_id: f46a1f21-a9e9-415a-9e2d-8b8303fe1659
  sha: c9f4099ecf2772b53c2dd4a8e508064ce015d182
  size: 1118845
jumpbox/cloudfoundry-utils/cert_generator:
  object_id: f2d07b02-3927-4015-9bc6-922cd41cf2ce
  sha: 853eb37ad3c9ffa7e5dc88ca3dbc5b55c6c0be1a
  size: 6667
jumpbox/cloudfoundry-utils/cf-app-env-json:
  object_id: 4e7ffcc2-5331-4d87-8a4b-13c2d61dc89c
  sha: b5b76fe615821b8ebbdfb626fc2b8ee48341e3db
  size: 610
jumpbox/cloudfoundry-utils/cf-apps-for-route:
  object_id: 65921c66-da29-4317-a02e-12108b8801b5
  sha: 353eeead0e21cc8a0a02c652aa07c6c8edb0daa6
  size: 2456
jumpbox/cloudfoundry-utils/cf-list-org-names:
  object_id: 03d55938-3d91-4459-8ada-5a513db689b3
  sha: 4f5903caa03ec1c384790b6ee8b1cf3da054892a
  size: 472
jumpbox/cloudfoundry-utils/cf-services-for-broker:
  object_id: a0e7a71e-ca61-4e15-9378-694636316435
  sha: adceb1b4d7b3b86ba831318d5a7f27f8cce28934
  size: 4761
jumpbox/cloudfoundry-utils/cf-verify:
  object_id: 0fc4b29c-cd90-48ef-89b4-70bcdfed4561
  sha: 8944c5834b65ccb82255a18755142a96018240cb
  size: 3820
jumpbox/cloudfoundry-utils/release-differ:
  object_id: d4c6986b-b1fa-4584-8c6c-86ccb5a9eddf
  sha: 87bfb4ffafafc9ec2c98069590c55cd8e3e7980c
  size: 2199
jumpbox/bins/terraform:
  object_id: 7f80b216-fcd7-4e5b-855f-bc7db5cca507
  sha: 07772a350cac3a3cb8791d778a6f470c30118ae1
  size: 93508352
