golang/go1.17.8.linux-amd64.tar.gz:
  size: 134902354
  object_id: f7f706f7-aa75-4929-6910-3c0ef2021618
  sha: sha256:980e65a863377e69fd9b67df9d8395fd8e93858e7a24c9f55803421e453f4f99
jumpbox/bins/bbr:
  size: 13811834
  object_id: 22377fee-40c2-4df0-4887-92fd16712ced
  sha: sha256:8a2fa6650938fb2184d99cb0a5b0b8ca7d36a77489d07d1d0fcaa41ed219bce8
jumpbox/bins/bosh:
  size: 35997988
  object_id: 44481156-351b-4a13-736c-089e34dd385e
  sha: sha256:bac6d4ee6b735b2ad061727b4abb7ec12d687b7274a10174dc18b84903380f40
jumpbox/bins/certstrap:
  size: 6191115
  object_id: 5e18df77-426d-49e1-794a-d3fd202d7034
  sha: sha256:db0007333f5285e8b4f42f684e3a9023e910f8955eb2471c4d65748d37b8b35b
jumpbox/bins/cf:
  size: 24756224
  object_id: a7c51b3c-9390-4dfe-443a-6289a28f2fc3
  sha: sha256:6e349ba8146d9e907847e8b7a522fc89d105976fbc5b5f008888b529a4727d1a
jumpbox/bins/cf7:
  size: 20205568
  object_id: 2fa3ac8d-b09d-4cbc-5dd5-8ead17d1137d
  sha: sha256:26ea956761778d57322fc807f70a7c34064067c4a7e01d90ec86422f46b5504f
jumpbox/bins/cf8:
  size: 24645632
  object_id: 4f95adcd-03ee-4eb6-6ffe-6b267c4558bd
  sha: sha256:fc1c7fbb2a566f63ff729b4d7d408cf1fbe6ac3594bd66d342eb181077262bf6
jumpbox/bins/credhub:
  size: 9132646
  object_id: cc134550-a7b8-428e-4718-5b5a9287abc0
  sha: sha256:c01a93258c955e80d155470bb2fd9c13bf5b73aea95093e6c29ee574dfdad009
jumpbox/bins/esuf:
  size: 7305569
  object_id: 94d813c4-8015-491b-6184-b5e52c16747a
  sha: sha256:bf1167d997de732bbbc8ecbd9caf368af6a588c97041490fe3ccfe6d60cc6095
jumpbox/bins/fly:
  size: 74509718
  object_id: 5554a2ed-4cee-4390-7cfd-c140570dca46
  sha: sha256:378def73d3fe12841a872fca2665d35dfc7247ab59d5363eaf3c3c3f69a07701
jumpbox/bins/genesis:
  size: 265141
  object_id: 7d5f1d26-daf6-42af-54ce-fe4cd2f4269e
  sha: sha256:13d84f336fe949cb364e92d7f33e4a74b789b2ad3e00e0de3c3ad735a4e85404
jumpbox/bins/jq:
  size: 3953824
  object_id: 2416f476-efeb-4d53-69b3-a5cc8962636f
  sha: sha256:af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44
jumpbox/bins/nats:
  size: 7014586
  object_id: b6a19bbf-5675-49bd-6995-2f044be4adba
  sha: sha256:3e353d9070798d35c334ebe8fc196988bac942c70cb1231bbc8e4e0c3077565e
jumpbox/bins/safe:
  size: 10159442
  object_id: 103f133e-5ecc-4f29-5794-774a6258b87e
  sha: sha256:25def65ba2be52e4f42c3e1d6bc2f67b5307cfbfd9e8e11a65af06e995bcf558
jumpbox/bins/shield:
  size: 8557697
  object_id: eabe4e8b-7c92-4ed3-5708-35aec3a2a82d
  sha: sha256:a6dd76f36339f92af910f3e6a8ef82228eb1545dcba1021c2cf5ac8f834e46f9
jumpbox/bins/spiff:
  size: 4808407
  object_id: 07cbb1a8-7424-456f-696a-78dd5552a27c
  sha: sha256:723eb37dacdd01cec106bb194a7bddeff5a3cb7882ec50b5f5265da9e8212710
jumpbox/bins/spruce:
  size: 21334068
  object_id: ff48d9fd-2ee1-4ce6-602f-00f943bbbd03
  sha: sha256:fb8e5021d7b330f05c9bc76d2dd953b3f2812a2414816a03f2a5a33eb99e70f6
jumpbox/bins/terraform:
  size: 63262720
  object_id: 74d2c27f-7dc7-4eb2-4538-a89835a402ed
  sha: sha256:ba86f524c64a97df436d541e67480607d0330ea27b23c3208316260189210151
jumpbox/bins/tmate:
  size: 3135320
  object_id: 1556169c-020e-44e4-5892-995890c24d99
  sha: sha256:d2fff992e40ce18ff81b9a92fa1cb93a56fb5a82c1cc428204552d8dfa1bc04f
jumpbox/bins/vault:
  size: 188378621
  object_id: 8cd5b321-9288-4951-527a-322c3ab14630
  sha: sha256:6c27b822dbe38e530fafcf8e15ab197a14451f977b21f3cacf9e9e42e27da253
jumpbox/bins/yq:
  size: 10160405
  object_id: a43b7c03-11f9-44bd-4605-18614787ad1a
  sha: sha256:042f7462ec8378f8b0d3bac85d1b1a063b63beef5d8e3826bb2377294116ae90
jumpbox/cloudfoundry-utils//cert_generator:
  size: 6667
  object_id: 5aebab56-9a99-4335-75da-82a50da559c8
  sha: sha256:3d73ca8ba53b8b640aaa3c3661122d1f138dff49424e86a573512a9ff19de9e5
jumpbox/cloudfoundry-utils//cf-app-env-json:
  size: 610
  object_id: 8a1cd94a-b2cc-4cf5-79a0-f2190654320b
  sha: sha256:3b9772d6bffb06415a8a7e627bbcab6879ef45024155b5126aea0fcbc7f6566a
jumpbox/cloudfoundry-utils//cf-apps-for-route:
  size: 2456
  object_id: 897eaa31-247c-4a55-67b9-5152baaa1892
  sha: sha256:84be46efa082f8b2cf6256998203f36d4190785ebb6c8b064c40e7b3b11796d9
jumpbox/cloudfoundry-utils//cf-list-org-names:
  size: 472
  object_id: a0b9394b-c2ca-4cd0-5e09-3be0176da0ec
  sha: sha256:1749efe944319a53de6c0a0362c91a86c92b6a274b8fcac83847974dffc5b499
jumpbox/cloudfoundry-utils//cf-services-for-broker:
  size: 4761
  object_id: 3590ea0c-48a7-4b07-4aef-a0e85f0ff1f5
  sha: sha256:0fe41d69984033e7dcd4553185ad6172719e6050303d349357b0bb39cf00dbfc
jumpbox/cloudfoundry-utils//cf-verify:
  size: 3820
  object_id: 0ed5fa63-a267-4dab-753f-465a0968f0f6
  sha: sha256:f004210c625fa78f6a16228f97094fceaaa4b2567229719c9a3cb127aead44ae
jumpbox/cloudfoundry-utils//commit_sha:
  size: 40
  object_id: 421e6013-47db-4f0f-5b37-387734e7c88b
  sha: sha256:6e43a278b50bc426ebde3a6665c0c8f02d50590e29852d5811479838cf59e3bb
jumpbox/cloudfoundry-utils//release-differ:
  size: 2199
  object_id: 50a037dd-1989-4178-4ce9-f4ff27aec50f
  sha: sha256:ae517eb0fce65c4a238b362c9861778ccad4a8d476f21d26a16dea291a00e203
jumpbox/curl-7.81.0.tar.gz:
  size: 4188040
  object_id: 42fb5db3-1f4c-40d9-7910-bea6567c0b44
  sha: sha256:ac8e1087711084548d788ef18b9b732c8de887457b81f616fc681d1044b32f98
jumpbox/git-2.35.7.tar.gz:
  size: 10530007
  object_id: b1f6c2f4-5089-44d0-4a0d-3e176cbb1d12
  sha: sha256:fc849272a95cc7457091221a645fcd753b3b1984767ee3323fb6a0aa944bbcb4
jumpbox/libevent-2.1.12-stable.tar.gz:
  size: 1100847
  object_id: 853918f8-5529-47a8-7faf-2d68245d479d
  sha: sha256:92e6de1be9ec176428fd2367677e61ceffc2ee1cb119035037a27d346b0403bb
jumpbox/tmux-3.2a.tar.gz:
  size: 648394
  object_id: c795d961-e908-4f28-7632-f7816d2a9cef
  sha: sha256:551553a4f82beaa8dadc9256800bcc284d7c000081e47aa6ecbb6ff36eacd05f
jumpbox/tree-2.0.2.tar.gz:
  size: 57960
  object_id: 7d13bfdf-29b5-43a6-4e84-d7bc537bdc46
  sha: sha256:7d693a1d88d3c4e70a73e03b8dbbdc12c2945d482647494f2f5bd83a479eeeaf
jumpbox/unzip60.tar.gz:
  size: 1376845
  object_id: 7317d283-62f1-40d3-851a-10418da85106
  sha: abf7de8a4018a983590ed6f5cbd990d4740f8a22
jumpbox/vim-8.2.4528.tar.gz:
  size: 16185073
  object_id: e1f8a296-40b3-44a3-6604-dd85f988b157
  sha: sha256:10a7e2b089697f247501c5f269536ae736d21d9dbc2065f2517cfb18bf7d7184
jumpbox/wget-1.21.3.tar.gz:
  size: 5079864
  object_id: eba5bdf1-b13f-43ce-5eed-f0a7f9d502c9
  sha: sha256:5726bb8bc5ca0f6dc7110f6416e4bb7019e2d2ff5bf93d1ca2ffcc6656f220e5
jumpbox/zip30.tar.gz:
  size: 1118845
  object_id: f46a1f21-a9e9-415a-9e2d-8b8303fe1659
  sha: c9f4099ecf2772b53c2dd4a8e508064ce015d182
