golang_1.5/go1.5.3.linux-amd64.tar.gz:
  size: 80147269
  object_id: 5d8b0264-6ad9-405e-961f-4449dd9a180f
  sha: c5377eca4837968d043b681f00a852a262f0f5f6
jumpbox/bins/bosh:
  size: 27736768
  object_id: 1708b90f-6234-4720-41ac-ca886f1572c1
  sha: bf04be72daa7da0c9bbeda16fda7fc7b2b8af51e
jumpbox/bins/bosh-init:
  size: 11873378
  object_id: cb2b768c-b66f-4335-b97f-bb7ab80e1bf0
  sha: 7c8c42641900d60d4bab24488de25cdcba0cb4a8
jumpbox/bins/certstrap:
  size: 5493848
  object_id: 6050fa1f-105b-4ddb-8074-224e149b5c83
  sha: 1fa8434399124dd0b17c20c0c90bc34fb0ba16bf
jumpbox/bins/cf:
  size: 17144768
  object_id: 2a3c1b73-bec1-43fe-6497-2819b0e07fd6
  sha: caf7508434c835bd3e8ec7f0744b70150e503bc0
jumpbox/bins/credhub:
  size: 9730875
  object_id: ae9adbcb-fc8c-4c9a-6cb7-9868775a0f5c
  sha: ec7d4e5dbbe9d3f5364929ac435e1ae5b94b1393
jumpbox/bins/esuf:
  size: 7305569
  object_id: 7902014e-2f9c-4add-9e90-2fc00514f919
  sha: 73979dd7fcb704a0994d55c416340d2d3bcf16df
jumpbox/bins/fly:
  size: 16036735
  object_id: 214b5ab1-1351-4369-6925-9f120c48c59f
  sha: 87afcc6f09ccda7bd49d350ee574b6ac8c9e145c
jumpbox/bins/genesis:
  size: 186923
  object_id: e82247b8-06e4-4ed4-5dc5-120be8d6a70c
  sha: 164fc176b4244e3a7ddf7eb1537356f135c51e7c
jumpbox/bins/nats:
  size: 7040936
  object_id: 698b0c19-976d-4161-81f3-03b859fe55ff
  sha: 39f00b44c10e332df5f0bff518c1aa2a4dc74792
jumpbox/bins/safe:
  size: 7931166
  object_id: 128d606c-8ed7-48b1-4088-b644d467abf3
  sha: dd3cc7359487fe6d4d69d7d5ed48abc6b53632d9
jumpbox/bins/shield:
  size: 8175536
  object_id: 0fe0d6e1-8545-43d9-a84f-938594598963
  sha: 34d3dd2619ab3daa5639791caa6c8e70d842a6f2
jumpbox/bins/spiff:
  size: 5063744
  object_id: eefcc937-c44a-4298-a56d-5e7259137c7c
  sha: 7489aa87ad7f5b3b774fc8a03ccda65860b1374c
jumpbox/bins/terraform:
  size: 55358048
  object_id: 21c8a668-1426-4d5f-98d8-615d13bea308
  sha: 740453274030f6e8be341be27dc349619f929f90
jumpbox/bins/tmate:
  size: 2748936
  object_id: 3253b6dc-3e45-4dd2-b6ce-deb1147b853b
  sha: 7dae88002cfc9686fa90e1535e17a2eae22407ea
jumpbox/bins/vault:
  size: 59959512
  object_id: a7d6df95-8bc5-4090-950d-35d349557801
  sha: 39f140b287ac8b0df513aa4ceb6c50b800b8ce66
jumpbox/cloudfoundry-utils//body:
  size: 99
  object_id: 7005f80a-4e64-47a2-5445-9a7262862a03
  sha: 199c9d8250c18075289ab78d8f639e964a9e972c
jumpbox/cloudfoundry-utils//cert_generator:
  size: 6667
  object_id: 5b957baa-d8a7-4de1-4080-c879eda40c87
  sha: 853eb37ad3c9ffa7e5dc88ca3dbc5b55c6c0be1a
jumpbox/cloudfoundry-utils//cf-app-env-json:
  size: 610
  object_id: 59318878-f15a-4233-5ecd-a0908b52f12b
  sha: b5b76fe615821b8ebbdfb626fc2b8ee48341e3db
jumpbox/cloudfoundry-utils//cf-apps-for-route:
  size: 2456
  object_id: 6aa9d46f-db8c-42be-4c63-78e0d0288043
  sha: 353eeead0e21cc8a0a02c652aa07c6c8edb0daa6
jumpbox/cloudfoundry-utils//cf-list-org-names:
  size: 472
  object_id: 0fc9f383-2554-4d1d-6e6c-6551ffc09347
  sha: 4f5903caa03ec1c384790b6ee8b1cf3da054892a
jumpbox/cloudfoundry-utils//cf-services-for-broker:
  size: 4761
  object_id: 7bdcc080-803a-42e8-6ded-1bf7c148f500
  sha: adceb1b4d7b3b86ba831318d5a7f27f8cce28934
jumpbox/cloudfoundry-utils//cf-verify:
  size: 3820
  object_id: c9346f03-909e-4a5b-49e1-cb81d71411be
  sha: 8944c5834b65ccb82255a18755142a96018240cb
jumpbox/cloudfoundry-utils//release-differ:
  size: 2199
  object_id: 881977a0-3501-469c-4a5e-0b55668f9b9c
  sha: 87bfb4ffafafc9ec2c98069590c55cd8e3e7980c
jumpbox/cloudfoundry-utils//tag:
  size: 6
  object_id: 0102ac77-e69e-42aa-447a-02ba426f96d2
  sha: 7ac19ee157556944f6939fe82286468b89688712
jumpbox/cloudfoundry-utils//version:
  size: 5
  object_id: 403044ba-db1d-4aba-78ab-91d57e92902a
  sha: 91e95be6b6634e3c21072dfcd661146728694326
jumpbox/curl-7.50.3.tar.gz:
  size: 8908593
  object_id: dab8c17e-f200-423e-8421-27c80bcaa15d
  sha: be0065afc76a3d8568f5f78d8efddadb6310f9d7
jumpbox/git-2.14.1.tar.gz:
  size: 6987933
  object_id: 35a33b21-0dac-44c2-60de-2e12f4b5f8b6
  sha: e173270a5f224078e3f6c639937da5bd84045225
jumpbox/jq-1.5.tar.gz:
  size: 739309
  object_id: 68bdc70f-d6a7-4f31-b29b-e1da48c81371
  sha: 6eef3705ac0a322e8aa0521c57ce339671838277
jumpbox/libevent-2.0.22-stable.tar.gz:
  size: 854987
  object_id: a1541bd8-921a-4c62-9971-19260c2fde62
  sha: a586882bc93a208318c70fc7077ed8fca9862864
jumpbox/tmux-2.2.tar.gz:
  size: 466852
  object_id: 645ddc79-20dd-4145-8ee8-e39c57539ea4
  sha: 5ed1430bc7ef44c227e64e9401c686573dd0791a
jumpbox/tree-1.7.0.tar.gz:
  size: 47082
  object_id: 14f6d45c-aaeb-4dc3-89c9-5ff370553d49
  sha: 35bd212606e6c5d60f4d5062f4a59bb7b7b25949
jumpbox/unzip60.tar.gz:
  size: 1376845
  object_id: 7317d283-62f1-40d3-851a-10418da85106
  sha: abf7de8a4018a983590ed6f5cbd990d4740f8a22
jumpbox/vim-7.4.tar.bz2:
  size: 9843297
  object_id: f109912f-1ea4-4e05-b467-fbb2f93f30b9
  sha: 601abf7cc2b5ab186f40d8790e542f86afca86b7
jumpbox/vim-8.0.0386.tar.gz:
  size: 13000882
  object_id: e0bd5753-1931-420f-ad98-d7aa7a937a3d
  sha: 59b7649b1a057d49860fdc99e4b91401253abc88
jumpbox/wget-1.18.tar.gz:
  size: 3865525
  object_id: 4e1e8e75-739f-48b8-aff5-ad9b0073dd65
  sha: 28a82e7de2eed38516c7d6e172ec7b9e43dc6c66
jumpbox/zip30.tar.gz:
  size: 1118845
  object_id: f46a1f21-a9e9-415a-9e2d-8b8303fe1659
  sha: c9f4099ecf2772b53c2dd4a8e508064ce015d182
