jumpbox/bins/bbr:
  size: 16210444
  object_id: 2b372c5a-b693-4889-6e55-50e39b8e360f
  sha: sha256:3f7002a1a1e514f0910dc7ebda158ac09ab0c4598f0c8c3f5da70be4627ca564
jumpbox/bins/bosh:
  size: 65302805
  object_id: 38be551a-f55c-4e3a-75ea-edd72f1c2ac8
  sha: sha256:b9f2120de54dfdca1214ad3054391e8871209dde53238906fde1be106caae7e5
jumpbox/bins/certstrap:
  size: 6191115
  object_id: 5e18df77-426d-49e1-794a-d3fd202d7034
  sha: sha256:db0007333f5285e8b4f42f684e3a9023e910f8955eb2471c4d65748d37b8b35b
jumpbox/bins/cf:
  size: 24756224
  object_id: 646e12e4-ec11-4cc0-591b-6b318984f721
  sha: sha256:6e349ba8146d9e907847e8b7a522fc89d105976fbc5b5f008888b529a4727d1a
jumpbox/bins/cf7:
  size: 21618840
  object_id: df57b12f-6f23-474e-7588-cf6e4f6ad01a
  sha: sha256:ceed025097ed828bc9f2eb91568863be681332dd0c43ac3ece11f7cc14ee60e6
jumpbox/bins/cf8:
  size: 26480792
  object_id: e555b931-391e-45d3-7397-a1253151766a
  sha: sha256:5350bddaef6378fa58a1354ff9d198e62776326c7596d1085e51e6670668eb00
jumpbox/bins/credhub:
  size: 11424402
  object_id: ec6a6b4b-ac2b-43e7-67eb-094ceb990849
  sha: sha256:52c62220c2e3d2ad1cd083c7f3d6660eaabf2c5ef32bc1dee14e52caa124ce3f
jumpbox/bins/esuf:
  size: 7305569
  object_id: 7bf5269f-2f01-4557-7c2e-2b64b4278b27
  sha: sha256:bf1167d997de732bbbc8ecbd9caf368af6a588c97041490fe3ccfe6d60cc6095
jumpbox/bins/fly:
  size: 90618305
  object_id: df14fa14-d54c-407c-424d-00b7d106af17
  sha: sha256:c126f1be24086aea0fa06fecbd4e50956b68aca2b1b920b6fc8e3d0cdbcfa2a2
jumpbox/bins/genesis:
  size: 393337
  object_id: 94f97fbc-300c-4600-4dc9-7d52de35bbea
  sha: sha256:9db85ad2bac689e7f41e6a5e0a66ed363361a4d91d1ec295bd89b08b40f40e48
jumpbox/bins/jq:
  size: 3953824
  object_id: 2416f476-efeb-4d53-69b3-a5cc8962636f
  sha: sha256:af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44
jumpbox/bins/nats:
  size: 7014586
  object_id: b6a19bbf-5675-49bd-6995-2f044be4adba
  sha: sha256:3e353d9070798d35c334ebe8fc196988bac942c70cb1231bbc8e4e0c3077565e
jumpbox/bins/safe:
  size: 10378351
  object_id: 4b3ab753-b6da-44dd-751a-20b1c57ccba1
  sha: sha256:c8cd4e7fbdfad5155eff8b13ea0035922c7fd2aa74a0bedfbbba0aa3ab60e3da
jumpbox/bins/shield:
  size: 8557697
  object_id: eabe4e8b-7c92-4ed3-5708-35aec3a2a82d
  sha: sha256:a6dd76f36339f92af910f3e6a8ef82228eb1545dcba1021c2cf5ac8f834e46f9
jumpbox/bins/spiff:
  size: 4808407
  object_id: 07cbb1a8-7424-456f-696a-78dd5552a27c
  sha: sha256:723eb37dacdd01cec106bb194a7bddeff5a3cb7882ec50b5f5265da9e8212710
jumpbox/bins/spruce:
  size: 27798277
  object_id: 10fffc6d-3447-467b-45ed-034668a7439f
  sha: sha256:70545acf81eb6bed46a340377cce0a752e2adcf202939c7f67fb6a52b2fb4261
jumpbox/bins/terraform:
  size: 63262720
  object_id: 74d2c27f-7dc7-4eb2-4538-a89835a402ed
  sha: sha256:ba86f524c64a97df436d541e67480607d0330ea27b23c3208316260189210151
jumpbox/bins/tmate:
  size: 3135320
  object_id: 1556169c-020e-44e4-5892-995890c24d99
  sha: sha256:d2fff992e40ce18ff81b9a92fa1cb93a56fb5a82c1cc428204552d8dfa1bc04f
jumpbox/bins/vault:
  size: 188378621
  object_id: 8cd5b321-9288-4951-527a-322c3ab14630
  sha: sha256:6c27b822dbe38e530fafcf8e15ab197a14451f977b21f3cacf9e9e42e27da253
jumpbox/bins/yq:
  size: 10160405
  object_id: a43b7c03-11f9-44bd-4605-18614787ad1a
  sha: sha256:042f7462ec8378f8b0d3bac85d1b1a063b63beef5d8e3826bb2377294116ae90
jumpbox/cloudfoundry-utils//cert_generator:
  size: 6667
  object_id: 9f30cdad-49de-4f2a-5cd5-9999d258d5c1
  sha: sha256:3d73ca8ba53b8b640aaa3c3661122d1f138dff49424e86a573512a9ff19de9e5
jumpbox/cloudfoundry-utils//cf-app-env-json:
  size: 610
  object_id: 8b7bbb91-d721-4ec7-6969-eb9098da6cde
  sha: sha256:3b9772d6bffb06415a8a7e627bbcab6879ef45024155b5126aea0fcbc7f6566a
jumpbox/cloudfoundry-utils//cf-apps-for-route:
  size: 2456
  object_id: bc2a21bd-8c05-45c2-41ab-d1614daffad3
  sha: sha256:84be46efa082f8b2cf6256998203f36d4190785ebb6c8b064c40e7b3b11796d9
jumpbox/cloudfoundry-utils//cf-list-org-names:
  size: 472
  object_id: ad729715-042f-4d3a-6d5f-ac2e56ce1729
  sha: sha256:1749efe944319a53de6c0a0362c91a86c92b6a274b8fcac83847974dffc5b499
jumpbox/cloudfoundry-utils//cf-services-for-broker:
  size: 4761
  object_id: bd077025-54cd-4b48-5a93-1e4b686462ef
  sha: sha256:0fe41d69984033e7dcd4553185ad6172719e6050303d349357b0bb39cf00dbfc
jumpbox/cloudfoundry-utils//cf-verify:
  size: 3820
  object_id: b73b9bf7-8aad-4698-7df5-b60ea1d7f8b6
  sha: sha256:f004210c625fa78f6a16228f97094fceaaa4b2567229719c9a3cb127aead44ae
jumpbox/cloudfoundry-utils//commit_sha:
  size: 40
  object_id: b79b49bf-38bd-4e65-5ca0-af130cebe6cb
  sha: sha256:6e43a278b50bc426ebde3a6665c0c8f02d50590e29852d5811479838cf59e3bb
jumpbox/cloudfoundry-utils//release-differ:
  size: 2199
  object_id: c7394d83-c4f5-4cf5-5c16-f9cff216a760
  sha: sha256:ae517eb0fce65c4a238b362c9861778ccad4a8d476f21d26a16dea291a00e203
jumpbox/cloudfoundry-utils//timestamp:
  size: 20
  object_id: 6c7e7fcb-7c20-482b-7311-a184b940d73b
  sha: sha256:7e71bef310efabd5363b3beb06883a0d0732b32c2acffc4bf6d0ac9db6cc4c01
jumpbox/cloudfoundry-utils//url:
  size: 80
  object_id: cae33d8a-b86c-4877-4e06-ccfa5bea5c85
  sha: sha256:1f6100be329b0c7dd6bedde63666b12530f3fab5b057bfeeffe4a6b0a288d751
jumpbox/git-2.35.7.tar.gz:
  size: 10530007
  object_id: b1f6c2f4-5089-44d0-4a0d-3e176cbb1d12
  sha: sha256:fc849272a95cc7457091221a645fcd753b3b1984767ee3323fb6a0aa944bbcb4
jumpbox/libevent-2.1.12-stable.tar.gz:
  size: 1100847
  object_id: 853918f8-5529-47a8-7faf-2d68245d479d
  sha: sha256:92e6de1be9ec176428fd2367677e61ceffc2ee1cb119035037a27d346b0403bb
jumpbox/tmux-3.2a.tar.gz:
  size: 648394
  object_id: c795d961-e908-4f28-7632-f7816d2a9cef
  sha: sha256:551553a4f82beaa8dadc9256800bcc284d7c000081e47aa6ecbb6ff36eacd05f
jumpbox/tree-2.0.2.tar.gz:
  size: 57960
  object_id: 7d13bfdf-29b5-43a6-4e84-d7bc537bdc46
  sha: sha256:7d693a1d88d3c4e70a73e03b8dbbdc12c2945d482647494f2f5bd83a479eeeaf
jumpbox/vim-8.2.4528.tar.gz:
  size: 16185073
  object_id: e1f8a296-40b3-44a3-6604-dd85f988b157
  sha: sha256:10a7e2b089697f247501c5f269536ae736d21d9dbc2065f2517cfb18bf7d7184
jumpbox/wget-1.21.3.tar.gz:
  size: 5079864
  object_id: eba5bdf1-b13f-43ce-5eed-f0a7f9d502c9
  sha: sha256:5726bb8bc5ca0f6dc7110f6416e4bb7019e2d2ff5bf93d1ca2ffcc6656f220e5
