golang/go1.14.2.linux-amd64.tar.gz:
  size: 123658438
  object_id: 8545848e-eefe-43a3-6d0a-78f58af18417
  sha: sha256:6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3
jumpbox/bins/bbr:
  size: 12908524
  object_id: 55023276-82cb-4a89-7fc1-e29019c806c4
  sha: sha256:d47905aa9ab3039ecf40909456f75b9a1e8ddc5d1ecb9b091476eff730ad54c5
jumpbox/bins/bosh:
  size: 32587163
  object_id: 58b92794-c0bd-450f-5763-4f30757244f4
  sha: sha256:596abc123ddb676f081d375dc4672359fb1573c38d8dd3e8bdc4f3d2769783a1
jumpbox/bins/certstrap:
  size: 6191115
  object_id: 5e18df77-426d-49e1-794a-d3fd202d7034
  sha: sha256:db0007333f5285e8b4f42f684e3a9023e910f8955eb2471c4d65748d37b8b35b
jumpbox/bins/cf:
  size: 24756224
  object_id: a7c51b3c-9390-4dfe-443a-6289a28f2fc3
  sha: sha256:6e349ba8146d9e907847e8b7a522fc89d105976fbc5b5f008888b529a4727d1a
jumpbox/bins/cf7:
  size: 22073344
  object_id: 765fa314-17ac-4f81-69e8-e4489b5cf9fa
  sha: sha256:bfb5681651d975c97d82fb6cbff8d440ecaf4b342253948fbfce2e09318c3ea1
jumpbox/bins/cf8:
  size: 19140608
  object_id: 2795524f-5917-4ec4-6d5c-f76b2cc4353c
  sha: sha256:ccc2442e68b15157368ad60ebc16aa8c570c6149400b8602c00811b42c39ce5f
jumpbox/bins/credhub:
  size: 11575285
  object_id: 7283b318-255b-4ced-6ea8-b479e49d0cc3
  sha: sha256:c3ec7ed7f83c822f00b24abf7baf4204a572f66662acb126fba4c549eca6e4ba
jumpbox/bins/esuf:
  size: 7305569
  object_id: c2506b57-9ca5-4a7f-7716-88a27b124952
  sha: sha256:bf1167d997de732bbbc8ecbd9caf368af6a588c97041490fe3ccfe6d60cc6095
jumpbox/bins/fly:
  size: 64806186
  object_id: 9eb19673-7e5a-487c-4a1d-ee2e483d3a17
  sha: sha256:a93a733c50a10ec74a9e17b7f803d3dea8a4c99ad98d78db042dcac62fecc0b3
jumpbox/bins/genesis:
  size: 249803
  object_id: 8a4e9869-eeae-4ee7-5bd1-d0e5ecfae68c
  sha: sha256:f0c7ae3bc1b164bb9b8bea0d15b15b7f69dc4b012b4c2485d62718103703f665
jumpbox/bins/jq:
  size: 3953824
  object_id: 2416f476-efeb-4d53-69b3-a5cc8962636f
  sha: sha256:af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44
jumpbox/bins/nats:
  size: 7014586
  object_id: 1c724e5b-668d-4d0f-7896-f8892f5a92ca
  sha: sha256:3e353d9070798d35c334ebe8fc196988bac942c70cb1231bbc8e4e0c3077565e
jumpbox/bins/safe:
  size: 9982119
  object_id: 6688f439-3c3a-49b9-5dc7-090418681dfe
  sha: sha256:666a65837b34c60f96868f2b1e2c5fcf32aa3333a184ed3d36c2532654ffc4c0
jumpbox/bins/shield:
  size: 9486663
  object_id: 9bd7829a-64c1-4e7d-5fe5-5d713cdd33c6
  sha: sha256:eafe55a860852befd3ae8561eb8cfa52e28a7a8ee62c0fc58bfd449aa9bf7156
jumpbox/bins/spiff:
  size: 4808407
  object_id: 07cbb1a8-7424-456f-696a-78dd5552a27c
  sha: sha256:723eb37dacdd01cec106bb194a7bddeff5a3cb7882ec50b5f5265da9e8212710
jumpbox/bins/spruce:
  size: 24762847
  object_id: 59830633-2ae5-4f14-673b-75a17addba0d
  sha: sha256:6224d344f07f9abb84c656f43fe1e3181b279fb4ce8309837bcd1b80aa82b327
jumpbox/bins/terraform:
  size: 85561299
  object_id: 51ab8ba7-6480-46a6-46c9-14d8c416abaa
  sha: sha256:432c69434a8f093e02891a2a9e9c43558c233343972d03b3809bf6fd9a6f9659
jumpbox/bins/tmate:
  size: 3135320
  object_id: 1556169c-020e-44e4-5892-995890c24d99
  sha: sha256:d2fff992e40ce18ff81b9a92fa1cb93a56fb5a82c1cc428204552d8dfa1bc04f
jumpbox/bins/vault:
  size: 131163471
  object_id: 5361edc1-7b6a-4c52-58b9-368856110c98
  sha: sha256:23a8b157d1b9a9c4ed08f60c64866df4b95d729f9b14680c500c83f2be03d861
jumpbox/cloudfoundry-utils//cert_generator:
  size: 6667
  object_id: 5aebab56-9a99-4335-75da-82a50da559c8
  sha: sha256:3d73ca8ba53b8b640aaa3c3661122d1f138dff49424e86a573512a9ff19de9e5
jumpbox/cloudfoundry-utils//cf-app-env-json:
  size: 610
  object_id: 8a1cd94a-b2cc-4cf5-79a0-f2190654320b
  sha: sha256:3b9772d6bffb06415a8a7e627bbcab6879ef45024155b5126aea0fcbc7f6566a
jumpbox/cloudfoundry-utils//cf-apps-for-route:
  size: 2456
  object_id: 897eaa31-247c-4a55-67b9-5152baaa1892
  sha: sha256:84be46efa082f8b2cf6256998203f36d4190785ebb6c8b064c40e7b3b11796d9
jumpbox/cloudfoundry-utils//cf-list-org-names:
  size: 472
  object_id: a0b9394b-c2ca-4cd0-5e09-3be0176da0ec
  sha: sha256:1749efe944319a53de6c0a0362c91a86c92b6a274b8fcac83847974dffc5b499
jumpbox/cloudfoundry-utils//cf-services-for-broker:
  size: 4761
  object_id: 3590ea0c-48a7-4b07-4aef-a0e85f0ff1f5
  sha: sha256:0fe41d69984033e7dcd4553185ad6172719e6050303d349357b0bb39cf00dbfc
jumpbox/cloudfoundry-utils//cf-verify:
  size: 3820
  object_id: 0ed5fa63-a267-4dab-753f-465a0968f0f6
  sha: sha256:f004210c625fa78f6a16228f97094fceaaa4b2567229719c9a3cb127aead44ae
jumpbox/cloudfoundry-utils//commit_sha:
  size: 40
  object_id: 421e6013-47db-4f0f-5b37-387734e7c88b
  sha: sha256:6e43a278b50bc426ebde3a6665c0c8f02d50590e29852d5811479838cf59e3bb
jumpbox/cloudfoundry-utils//release-differ:
  size: 2199
  object_id: 50a037dd-1989-4178-4ce9-f4ff27aec50f
  sha: sha256:ae517eb0fce65c4a238b362c9861778ccad4a8d476f21d26a16dea291a00e203
jumpbox/curl-7.69.1.tar.gz:
  size: 4131634
  object_id: de4401d2-dbd5-4366-53ab-94f8eea3cf21
  sha: sha256:01ae0c123dee45b01bbaef94c0bc00ed2aec89cb2ee0fd598e0d302a6b5e0a98
jumpbox/git-2.26.0.tar.gz:
  size: 9276174
  object_id: b3c5fe48-70a2-4341-66da-bcb7fddc025b
  sha: sha256:aa168c2318e7187cd295a645f7370cc6d71a324aafc932f80f00c780b6a26bed
jumpbox/libevent-2.1.11-stable.tar.gz:
  size: 1082234
  object_id: f31efe13-0239-4607-7222-73e52e93d04f
  sha: sha256:a65bac6202ea8c5609fd5c7e480e6d25de467ea1917c08290c521752f147283d
jumpbox/tmux-3.0a.tar.gz:
  size: 546377
  object_id: b9b29ccd-f2fb-4e7c-6116-29a21aba0ecf
  sha: sha256:4ad1df28b4afa969e59c08061b45082fdc49ff512f30fc8e43217d7b0e5f8db9
jumpbox/tree-1.8.0.tar.gz:
  size: 50286
  object_id: 6b9863a1-f5fd-4543-4b1a-eab8abf73ed5
  sha: sha256:715d5d4b434321ce74706d0dd067505bb60c5ea83b5f0b3655dae40aa6f9b7c2
jumpbox/unzip60.tar.gz:
  size: 1376845
  object_id: 7317d283-62f1-40d3-851a-10418da85106
  sha: abf7de8a4018a983590ed6f5cbd990d4740f8a22
jumpbox/vim-8.2.0539.tar.gz:
  size: 14896238
  object_id: 4decc7bd-5787-43ce-7385-af2b571d7d27
  sha: sha256:643c7a877f60d74bedb6297c7ed2b0ae0b9cdf764e522b0d6d754e17ee057af2
jumpbox/wget-1.20.3.tar.gz:
  size: 4489249
  object_id: 1e08ca74-8399-4f99-7fd0-f771a22b5a15
  sha: sha256:31cccfc6630528db1c8e3a06f6decf2a370060b982841cfab2b8677400a5092e
jumpbox/zip30.tar.gz:
  size: 1118845
  object_id: f46a1f21-a9e9-415a-9e2d-8b8303fe1659
  sha: c9f4099ecf2772b53c2dd4a8e508064ce015d182
