golang/go1.11.4.linux-amd64.tar.gz:
  size: 126643341
  object_id: 18a5e777-2d8d-4bac-72c1-ab01f14186f2
  sha: 52bd8eb353a39138a2ddf053857a0fd13f1f176c
jumpbox/bins/bosh:
  size: 27736768
  object_id: 1708b90f-6234-4720-41ac-ca886f1572c1
  sha: bf04be72daa7da0c9bbeda16fda7fc7b2b8af51e
jumpbox/bins/bosh-init:
  size: 11873378
  object_id: cb2b768c-b66f-4335-b97f-bb7ab80e1bf0
  sha: 7c8c42641900d60d4bab24488de25cdcba0cb4a8
jumpbox/bins/certstrap:
  size: 5493848
  object_id: 6050fa1f-105b-4ddb-8074-224e149b5c83
  sha: 1fa8434399124dd0b17c20c0c90bc34fb0ba16bf
jumpbox/bins/cf:
  size: 20400448
  object_id: 01552566-a0fe-406d-78a4-cd479f2738dd
  sha: 6cdab8209546953e16e232e5751ec84982548d3a
jumpbox/bins/credhub:
  size: 9707378
  object_id: d5bdf8e1-d4cf-49ba-5953-1c2182d6abee
  sha: 474f29af45ebec8da4425f6b8c3db4b8cdcff76c
jumpbox/bins/esuf:
  size: 7305569
  object_id: d02e9d51-4801-4232-57f3-bf1c0236070a
  sha: 73979dd7fcb704a0994d55c416340d2d3bcf16df
jumpbox/bins/fly:
  size: 14045212
  object_id: 4a942add-617a-4ea1-66a4-50b481b7e3aa
  sha: 0502422d544f820ee07de7194758824af36f19ea
jumpbox/bins/genesis:
  size: 189586
  object_id: b4f1a73a-bd84-42e2-5352-403ef6a66ef4
  sha: 9e8a50165cecffb0314d260737ca0234a2030532
jumpbox/bins/jq:
  size: 3027945
  object_id: d2d8fb46-86fb-4df8-4b84-3da06ffda574
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
jumpbox/bins/nats:
  size: 7040936
  object_id: 698b0c19-976d-4161-81f3-03b859fe55ff
  sha: 39f00b44c10e332df5f0bff518c1aa2a4dc74792
jumpbox/bins/safe:
  size: 8297087
  object_id: 57385d07-4a95-4d45-45e1-b270290c2344
  sha: e44ea5ccf1ba783f88fadcdbca2e4d4a5d2099b2
jumpbox/bins/shield:
  size: 8175536
  object_id: 0fe0d6e1-8545-43d9-a84f-938594598963
  sha: 34d3dd2619ab3daa5639791caa6c8e70d842a6f2
jumpbox/bins/spiff:
  size: 5063744
  object_id: eefcc937-c44a-4298-a56d-5e7259137c7c
  sha: 7489aa87ad7f5b3b774fc8a03ccda65860b1374c
jumpbox/bins/terraform:
  size: 89483552
  object_id: f0c8112b-a7c3-4722-7f55-fb3bf204742c
  sha: 8d62bbc6e6a13851e087d3d13bc65377375c35da
jumpbox/bins/tmate:
  size: 2748936
  object_id: 3253b6dc-3e45-4dd2-b6ce-deb1147b853b
  sha: 7dae88002cfc9686fa90e1535e17a2eae22407ea
jumpbox/bins/vault:
  size: 85734099
  object_id: 776aec93-754d-44a4-4262-12efa2e68844
  sha: d0e1eedba1570e9eae59eccdb2f2ba640acff49a
jumpbox/cloudfoundry-utils//cert_generator:
  size: 6667
  object_id: 87a07bb8-50d5-4f04-4cef-3746e79dba76
  sha: 853eb37ad3c9ffa7e5dc88ca3dbc5b55c6c0be1a
jumpbox/cloudfoundry-utils//cf-app-env-json:
  size: 610
  object_id: a21b0a73-1e8b-472b-7835-b27cb28dcf89
  sha: b5b76fe615821b8ebbdfb626fc2b8ee48341e3db
jumpbox/cloudfoundry-utils//cf-apps-for-route:
  size: 2456
  object_id: 89c7e05e-b54e-4376-6147-fc6e6f81da98
  sha: 353eeead0e21cc8a0a02c652aa07c6c8edb0daa6
jumpbox/cloudfoundry-utils//cf-list-org-names:
  size: 472
  object_id: ee24abf7-335a-46b4-5898-1d89b5dfaf90
  sha: 4f5903caa03ec1c384790b6ee8b1cf3da054892a
jumpbox/cloudfoundry-utils//cf-services-for-broker:
  size: 4761
  object_id: fd942438-4323-47d5-6df8-2923e73540ce
  sha: adceb1b4d7b3b86ba831318d5a7f27f8cce28934
jumpbox/cloudfoundry-utils//cf-verify:
  size: 3820
  object_id: 752fb9d9-7c01-46cf-45d7-03355c88d3cf
  sha: 8944c5834b65ccb82255a18755142a96018240cb
jumpbox/cloudfoundry-utils//commit_sha:
  size: 40
  object_id: 6faadf93-8a27-484f-47a2-ce65d29ad793
  sha: f44dbdc4ade1d5f62684eaf707d7494a37cb2e6a
jumpbox/cloudfoundry-utils//release-differ:
  size: 2199
  object_id: 3ba4d4c4-7b4c-4e66-61f0-275eed2737a3
  sha: 87bfb4ffafafc9ec2c98069590c55cd8e3e7980c
jumpbox/curl-7.63.0.tar.gz:
  size: 4024015
  object_id: d7215770-b813-458d-7099-8e80814c43b2
  sha: b2cb51ac6451728dda191f307db30797629ca14d
jumpbox/git-2.20.1.tar.gz:
  size: 7962304
  object_id: 2cf0a85d-350e-416d-4a01-cd6a9978fe6f
  sha: 6439fb9afc9366f7bf1ddf8bfbe59998e0450ed3
jumpbox/libevent-2.1.8-stable.tar.gz:
  size: 1026485
  object_id: 6ff08733-8696-43ac-7df5-bd0751fef1fd
  sha: 2a1b8bb7a262d3fd0ed6a080a20991a6eed675ec
jumpbox/tmux-2.8.tar.gz:
  size: 491195
  object_id: 96975804-9732-45a4-69d2-4fa8e76a6ab1
  sha: 6a469769a242c95dc8aec443b436d4f8f279f517
jumpbox/tree-1.7.0.tar.gz:
  size: 47082
  object_id: 14f6d45c-aaeb-4dc3-89c9-5ff370553d49
  sha: 35bd212606e6c5d60f4d5062f4a59bb7b7b25949
jumpbox/unzip60.tar.gz:
  size: 1376845
  object_id: 7317d283-62f1-40d3-851a-10418da85106
  sha: abf7de8a4018a983590ed6f5cbd990d4740f8a22
jumpbox/vim-8.1.0789.tar.gz:
  size: 14061297
  object_id: d85b9def-f1bd-40e5-7708-4bb11d40f0df
  sha: bfa10769ca8021316cade7811487f76060e804ab
jumpbox/wget-1.20.tar.gz:
  size: 4474641
  object_id: 5a8f0603-97cc-4bc1-7f9e-ab2ef1f85577
  sha: 467c0ec7dab302cf1826970c1925999d64a6ee9d
jumpbox/zip30.tar.gz:
  size: 1118845
  object_id: f46a1f21-a9e9-415a-9e2d-8b8303fe1659
  sha: c9f4099ecf2772b53c2dd4a8e508064ce015d182
